### ISSUE TITLE
Design Article page

### ISSUE THREAD

**Issue by Okewunmi1** [zuri-training/Team-39-project-my-debtors#55]
The article page was designed by Ideraoluwao and was redesigned by Okewunmi1.
The link to our article page designs is in the figma link below
https://www.figma.com/file/xweedyiijgngZt24JB44rd/Team-39_MyDebtors-Figma?node-id=305%3A98

**Comment by Okewunmi1** [comment]
This is a link to the Hifi design of the article page i did
https://www.figma.com/file/xweedyiijgngZt24JB44rd/Team-39_MyDebtors-Figma?node-id=2056%3A13859

**Comment by IderaoluwaO** [comment]
Here is a link to the lo-fi design of the article page: https://www.figma.com/file/xweedyiijgngZt24JB44rd/Team-39_MyDebtors-Figma?node-id=2222%3A18397
Hi
